# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Create Results dir
      run: |
        mkdir src/Results
    - name: Make upload script executable
      run: chmod +x ./utils/uploadFiles.sh
    - name: Restore dependencies
      run: dotnet restore src/TestApp.sln
    - name: Build
      run: dotnet build src/TestApp.sln --no-restore
    - name: Unit Tests
      run: dotnet test src/Tests/TestApp.UnitTests/TestApp.UnitTests.csproj --no-build --verbosity normal
    - name: Component Tests
      run: dotnet test src/Tests/TestApp.ComponentTests/TestApp.ComponentTests.csproj --no-build --verbosity normal
    - name: Upload Unit Tests
      run: ./utils/uploadFiles.sh   -u ${{ secrets.ALLUREURL }} -r "../src/Results/unit-allure-results"   -o "unit-allure-results.json" -U ${{ secrets.ALLUREUSER }} -P ${{ secrets.ALLUREPASSWORD }} 
    - name: Upload Component Tests
      run: ./utils/uploadFiles.sh   -u ${{ secrets.ALLUREURL }}  -r "../src/Results/component-allure-results"   -o "component-allure-results.json"  -U ${{ secrets.ALLUREUSER }} -P ${{ secrets.ALLUREPASSWORD }} 